# Generated by Django 2.1.7 on 2020-08-27 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID')),
                ('product_id', models.IntegerField(blank=True, null=True, verbose_name='商品ID')),
                ('product_amount', models.IntegerField(blank=True, null=True, verbose_name='加入购物车商品数量')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='商品单价')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='加入购物车时间')),
                ('created_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 27, 14, 51, 58, 167090), null=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'ord_order_cart',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='订单表自增ID')),
                ('product_id', models.IntegerField(blank=True, null=True, verbose_name='订单商品自增ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名称')),
                ('product_count', models.FloatField(blank=True, default=1.0, null=True, verbose_name='购买商品数量')),
                ('product_price', models.FloatField(blank=True, null=True, verbose_name='购买商品单价')),
                ('average_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='平均成本价格')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='商品重量')),
                ('fee_money', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='优惠分摊金额')),
                ('warehouse_id', models.IntegerField(blank=True, null=True, verbose_name='仓库ID')),
                ('modify_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 27, 14, 51, 58, 166099), null=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'db_table': 'ord_order_detail',
            },
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=255, verbose_name='订单编号 yyyymmddnnnnnnnn')),
                ('user_id', models.IntegerField(verbose_name='下单人(用户)ID')),
                ('shipping_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='收货人姓名')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='市')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='区')),
                ('address', models.TextField(blank=True, null=True, verbose_name='详细地址')),
                ('payment_method', models.CharField(blank=True, max_length=8, null=True, verbose_name='支付方式：1：现金，2：余额，3：网银，4：支付宝，5：微信')),
                ('order_money', models.FloatField(blank=True, null=True, verbose_name='订单金额')),
                ('discount_money', models.FloatField(blank=True, null=True, verbose_name='优惠金额')),
                ('shipping_money', models.FloatField(blank=True, null=True, verbose_name='运费金额')),
                ('payment_money', models.FloatField(blank=True, null=True, verbose_name='支付金额')),
                ('shipping_company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='快递公司名称')),
                ('shipping_sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='快递单号')),
                ('created_time', models.DateTimeField(blank=True, null=True, verbose_name='下单时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('shipping_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('receive_time', models.DateTimeField(blank=True, null=True, verbose_name='收货时间')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='交易完成时间')),
                ('close_time', models.DateTimeField(blank=True, null=True, verbose_name='交易关闭时间')),
                ('order_status', models.CharField(blank=True, max_length=8, null=True, verbose_name='订单状态，0：已取消，1：待支付，2：已支付，3：已发货，4：交易成功，5：交易关闭')),
                ('order_point', models.IntegerField(blank=True, default=0, null=True, verbose_name='订单积分')),
                ('invoice_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='发票抬头')),
                ('modify_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 27, 14, 51, 58, 166099), null=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '主订单',
                'verbose_name_plural': '主订单',
                'db_table': 'ord_order_master',
            },
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='物流公司名称')),
                ('ship_contact', models.CharField(blank=True, max_length=32, null=True, verbose_name='物流公司联系人')),
                ('telephone', models.CharField(blank=True, max_length=32, null=True, verbose_name='物流公司联系电话')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='配送价格')),
                ('modify_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 27, 14, 51, 58, 169093), null=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '物流公司信息',
                'verbose_name_plural': '物流公司信息',
                'db_table': 'ord_shipping_info',
            },
        ),
        migrations.CreateModel(
            name='WarehouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_sn', models.CharField(blank=True, max_length=32, null=True, verbose_name='仓库编码')),
                ('warehouse_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='仓库名称')),
                ('warehouse_phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='仓库电话')),
                ('contact', models.CharField(blank=True, max_length=32, null=True, verbose_name='仓库联系人')),
                ('province', models.CharField(blank=True, max_length=32, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='市')),
                ('district', models.CharField(blank=True, max_length=32, null=True, verbose_name='区')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='仓库地址')),
                ('warehouse_status', models.CharField(blank=True, max_length=8, null=True, verbose_name='仓库状态：0：禁用，1：启用')),
                ('modify_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 27, 14, 51, 58, 168091), null=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '仓库信息',
                'verbose_name_plural': '仓库信息',
                'db_table': 'ord_warehouse_info',
            },
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='商品ID')),
                ('warehouse_id', models.IntegerField(verbose_name='仓库ID')),
                ('current_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='当前商品总数')),
                ('lock_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='当前占用数量')),
                ('in_transit_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='在途数量')),
                ('average_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='移动加权成本')),
                ('modify_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 27, 14, 51, 58, 168091), null=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '商品库存',
                'verbose_name_plural': '商品库存',
                'db_table': 'ord_warehouse_product',
            },
        ),
    ]
